# Generated by Django 4.2.3 on 2023-07-09 06:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
