# Generated by Django 4.2.2 on 2023-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_blog_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='portada',
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog_images/'),
        ),
    ]
